import type { Book, Order, Notification } from "@/lib/types"

export const books: Book[] = [
  {
    id: "book-1",
    title: "The Midnight Library",
    author: "Matt Haig",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different, if you had the chance to undo your regrets?",
    price: 14.99,
    originalPrice: 24.99,
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4,
    reviews: 2547,
    genre: "Fiction",
    isNew: false,
    isBestseller: true,
    publisher: "Viking",
    publicationDate: "August 13, 2020",
    pages: 304,
    language: "English",
    isbn: "978-0525559474",
  },
  {
    id: "book-2",
    title: "Atomic Habits",
    author: "James Clear",
    description:
      "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    price: 11.99,
    originalPrice: 27.0,
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 5,
    reviews: 4289,
    genre: "Non-Fiction",
    isNew: false,
    isBestseller: true,
    publisher: "Avery",
    publicationDate: "October 16, 2018",
    pages: 320,
    language: "English",
    isbn: "978-0735211292",
  },
  {
    id: "book-3",
    title: "Project Hail Mary",
    author: "Andy Weir",
    description:
      "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it.",
    price: 14.99,
    originalPrice: 28.99,
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 5,
    reviews: 1876,
    genre: "Science Fiction",
    isNew: true,
    isBestseller: false,
    publisher: "Ballantine Books",
    publicationDate: "May 4, 2021",
    pages: 496,
    language: "English",
    isbn: "978-0593135204",
  },
  {
    id: "book-4",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description:
      "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    price: 12.99,
    originalPrice: 26.99,
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4,
    reviews: 3241,
    genre: "Mystery",
    isNew: false,
    isBestseller: true,
    publisher: "Celadon Books",
    publicationDate: "February 5, 2019",
    pages: 336,
    language: "English",
    isbn: "978-1250301697",
  },
  {
    id: "book-5",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    description:
      "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl. But Kya is not what they say.",
    price: 9.99,
    originalPrice: 18.0,
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4,
    reviews: 5678,
    genre: "Fiction",
    isNew: false,
    isBestseller: true,
    publisher: "G.P. Putnam's Sons",
    publicationDate: "August 14, 2018",
    pages: 384,
    language: "English",
    isbn: "978-0735219090",
  },
  {
    id: "book-6",
    title: "The Four Winds",
    author: "Kristin Hannah",
    description:
      "Texas, 1934. Millions are out of work and a drought has broken the Great Plains. Farmers are fighting to keep their land and their livelihoods as the crops are failing, the water is drying up, and dust threatens to bury them all. One of the darkest periods of the Great Depression, the Dust Bowl era, has arrived with a vengeance.",
    price: 14.99,
    originalPrice: 28.99,
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4,
    reviews: 2134,
    genre: "Historical Fiction",
    isNew: true,
    isBestseller: false,
    publisher: "St. Martin's Press",
    publicationDate: "February 2, 2021",
    pages: 464,
    language: "English",
    isbn: "978-1250178602",
  },
  {
    id: "book-7",
    title: "The Vanishing Half",
    author: "Brit Bennett",
    description:
      "The Vignes twin sisters will always be identical. But after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything: their families, their communities, their racial identities.",
    price: 13.99,
    originalPrice: 27.0,
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4,
    reviews: 1987,
    genre: "Fiction",
    isNew: false,
    isBestseller: false,
    publisher: "Riverhead Books",
    publicationDate: "June 2, 2020",
    pages: 352,
    language: "English",
    isbn: "978-0525536291",
  },
  {
    id: "book-8",
    title: "Educated",
    author: "Tara Westover",
    description:
      "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education, and no one to intervene when one of Tara's older brothers became violent.",
    price: 12.99,
    originalPrice: 28.0,
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 5,
    reviews: 4321,
    genre: "Biography",
    isNew: false,
    isBestseller: true,
    publisher: "Random House",
    publicationDate: "February 20, 2018",
    pages: 352,
    language: "English",
    isbn: "978-0399590504",
  },
]

export const featuredBooks: Book[] = books.filter((book) => book.isBestseller).slice(0, 4)

export const orders: Order[] = [
  {
    id: "ORD-2023-1001",
    date: "2023-03-15T10:30:00",
    status: "delivered",
    items: [
      {
        title: "The Midnight Library",
        author: "Matt Haig",
        price: 14.99,
        quantity: 1,
      },
      {
        title: "Atomic Habits",
        author: "James Clear",
        price: 11.99,
        quantity: 1,
      },
    ],
    subtotal: 26.98,
    shipping: 4.99,
    tax: 2.7,
    total: 34.67,
    shipping_address: {
      name: "John Doe",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "United States",
    },
  },
  {
    id: "ORD-2023-1002",
    date: "2023-04-22T14:45:00",
    status: "shipped",
    items: [
      {
        title: "Project Hail Mary",
        author: "Andy Weir",
        price: 14.99,
        quantity: 1,
      },
    ],
    subtotal: 14.99,
    shipping: 4.99,
    tax: 1.5,
    total: 21.48,
    shipping_address: {
      name: "John Doe",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "United States",
    },
  },
  {
    id: "ORD-2023-1003",
    date: "2023-05-10T09:15:00",
    status: "processing",
    items: [
      {
        title: "The Four Winds",
        author: "Kristin Hannah",
        price: 14.99,
        quantity: 1,
      },
      {
        title: "The Vanishing Half",
        author: "Brit Bennett",
        price: 13.99,
        quantity: 1,
      },
      {
        title: "Educated",
        author: "Tara Westover",
        price: 12.99,
        quantity: 1,
      },
    ],
    subtotal: 41.97,
    shipping: 0.0,
    tax: 4.2,
    total: 46.17,
    shipping_address: {
      name: "John Doe",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "United States",
    },
  },
]

export const notifications: Notification[] = [
  {
    id: "notif-1",
    title: "Order Shipped",
    message: "Your order #ORD-2023-1002 has been shipped and is on its way!",
    type: "delivery",
    date: "2023-04-23T10:15:00",
    isRead: false,
    action: "Track Order",
    actionLink: "/account?tab=orders",
  },
  {
    id: "notif-2",
    title: "New Order Confirmation",
    message: "Thank you for your order #ORD-2023-1003. We're processing it now.",
    type: "order",
    date: "2023-05-10T09:20:00",
    isRead: false,
    action: "View Order",
    actionLink: "/account?tab=orders",
  },
  {
    id: "notif-3",
    title: "Summer Reading Sale",
    message: "Enjoy 20% off on all fiction books until June 30th!",
    type: "promotion",
    date: "2023-06-01T08:00:00",
    isRead: true,
    action: "Shop Now",
    actionLink: "/bookstore",
  },
  {
    id: "notif-4",
    title: "Free Book with Purchase",
    message: "Spend $50 or more and get a free mystery book with your order!",
    type: "gift",
    date: "2023-05-15T12:30:00",
    isRead: true,
  },
  {
    id: "notif-5",
    title: "Order Delivered",
    message: "Your order #ORD-2023-1001 has been delivered. Enjoy your books!",
    type: "delivery",
    date: "2023-03-18T15:45:00",
    isRead: true,
  },
]

